import uuid from 'uuid'
import Decimal from 'decimal.js'

import time from './utils/time'
import Order from './Order'

export default class Trade {
  /**
   * unique trade id
   */
  id: string = uuid.v4()

  /**
   * fill price
   */
  fillPrice: Decimal

  /**
   * fill quantity
   */
  fillQuantity: Decimal

  /**
   * orders created by this trade execution (usually partial fill of a market
   * order)
   */
  newOrders:      Order[]

  /**
   * bid/ask order pair filled
   */
  matchedOrders:  Order[]

  /**
   * rejected unfillable orders
   */
  rejectedOrders: Order[]

  /**
   * unix time of execution
   */
  executedAt: number

  /**
   * trade constructor
   * @param fillPrice price that the trade was filled out
   * @param fillQuantity quantity that the trade was filled for
   * @param newOrders any orders generated by this trade (usually due to partial
   * fills)
   * @param matchedOrders pair of orders that were matched
   * @param rejectedOrders any orders that were generated but could not be
   * submitted
   * @param executedAt time of trade execution, defaults to unix time
   */
  constructor(
    fillQuantity: Decimal,
    fillPrice: Decimal,
    newOrders: Order[] = [],
    matchedOrders: Order[] = [],
    rejectedOrders: Order[] = [],
    executedAt: number = time().valueOf()
  ) {
    this.fillPrice = fillPrice
    this.fillQuantity = fillQuantity
    this.newOrders = newOrders
    this.matchedOrders = matchedOrders
    this.rejectedOrders = rejectedOrders
    this.executedAt = executedAt
  }
}
